- name: install and configure vsftpd, apache, php
  hosts: app
  become: true
  roles:
    - ftp
    - apache

- name: install mysql
  hosts: db
  become: true
  roles:
    - mysql

- name: install and deploy wp
  hosts: app
  become: true
  roles:
    - wp