- name: create app dir
  file:
    path: "{{ app_dir }}"
    state: directory

- name: download WordPress
  get_url: 
    url=https://wordpress.org/latest.tar.gz 
    dest=/tmp/wordpress.tar.gz
    
- name: extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest={{ app_dir }} copy=no

- name: Update WordPress config file
  template:
    src: "wp.conf.j2"
    dest: "{{ app_dir }}/wordpress/wp-config.php"